test:
  workers:
    type: local
    number: 1
  rounds:
   # - label: insert Patient
   #   txNumber: 15000
   #   rateControl:
   #     type: fixed-rate
   #     opts:
   #       tps: 35
   #   callback: benchmarks/samples/fabric/testeCouch/insertPatient.js
   # - label: insert D_Items
   #   txNumber: 15000
   #   rateControl:
   #     type: fixed-rate
   #     opts:
   #       tps: 50
   #   callback: benchmarks/samples/fabric/testeCouch/insertDitem.js
    - label: insert Prescription
      txNumber: 15000
      rateControl:
        type: fixed-rate
        opts:
          tps: 35
      callback: benchmarks/samples/fabric/testeCouch/insertPrescription.js
    - label: insert InputeventMv
      txNumber: 15000
      rateControl:
        type: fixed-rate
        opts:
          tps: 35
      callback: benchmarks/samples/fabric/testeCouch/insertInputeventMv.js
   # - label: query Patient by subjectId
   #   txNumber: 15000
   #   rateControl:
   #     type: fixed-rate
   #     opts:
   #       tps: 35
   #   callback: benchmarks/samples/fabric/testeCouch/queryPatientId.js 
monitor:
  type:
  - docker
  docker:
    names:
    - all
  interval: 1
